<?php

namespace AppBundle\Repository;

/**
 * DSDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DSDRepository extends \Doctrine\ORM\EntityRepository
{
}
